apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: authelia
  labels:
    name: redis
spec:
  selector:
    app: redis
  ports:
  - name: tcp
    protocol: TCP
    port: 6379
    targetPort: 6379
