apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- blocky-config.yaml
secretGenerator:
- name: env-secrets
  namespace: blocky
  envs:
  - env.txt
  type: Opaque