apiVersion: v1
kind: Service
metadata:
  name: authelia-server
  namespace: authelia
  labels:
    name: authelia-server
spec:
  selector:
    app: authelia-server
  ports:
  - name: http
    protocol: TCP
    port: 9091
    targetPort: 9091
