apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
spec:
  valuesContent: |-
    image:
      name: traefik
      tag: v2.7.0
    deployment:
      replicas: 1
    providers:
      kubernetesCRD:
        allowCrossNamespace: true
        
    logs:
      general:
        level: ERROR
      access:
        enabled: false
    ports:
      ssh-ha:
        port: 4005
        expose: true
        exposedPort: 4005
        protocol: TCP
      web:
        redirectTo: websecure
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
      websecure:
        http3: true
        tls:
          enabled: true
      irc:
        port: 16501
        expose: true
        exposedPort: 6501
        protocol: TCP
    service:
      enabled: true
      annotations:
        metallb.universe.tf/allow-shared-ip: "key-to-share-192.168.4.20"
        metallb.universe.tf/loadBalancerIPs: "192.168.4.20"
      spec:
        externalTrafficPolicy: Local
    experimental:
     http3:
       enabled: true
