namespace: wireguard
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- configmap.yaml
- deployment.yaml
- namespace.yaml
- service.yaml
images:
- name: docker.io/linuxserver/wireguard
  newTag: "1.0.20210914"
