apiVersion: v1
kind: Service
metadata:
  name: wireguard
  namespace: wireguard
  annotations:
    metallb.universe.tf/loadBalancerIPs: "192.168.4.21"
spec:
  type: LoadBalancer
  selector:
    app: wireguard
  ports:
  - name: 51820-tcp
    protocol: UDP
    port: 51820
    targetPort: 51820
