apiVersion: v1
kind: Service
metadata:
  name: znc
  namespace: znc
  labels:
    name: znc
spec:
  selector:
    app: znc
  ports:
  - name: irc
    protocol: TCP
    port: 6501
    targetPort: 6501
  - name: http
    protocol: TCP
    port: 6502
    targetPort: 6502
