apiVersion: v1
kind: Service
metadata:
  name: mariadb
  namespace: authelia
  labels:
    name: mariadb
spec:
  selector:
    app: mariadb
  ports:
  - name: tcp
    protocol: TCP
    port: 3306
    targetPort: 3306
