apiVersion: v1
kind: Secret
metadata:
  name: authelia-config
  namespace: authelia
stringData:
  configuration.yml: |
    server:
      host: 0.0.0.0
      port: 9091
      read_buffer_size: 4096
      write_buffer_size: 4096
    log:
      level: info
    theme: auto
    jwt_secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    default_redirection_url: https://yourdomain.com
    totp:
      disable: false
      issuer: yourdomain.com
      period: 30
      skew: 1
    duo_api:
      hostname: api-xxxxxxxxxxxx.duosecurity.com
      integration_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      secret_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      enable_self_enrollment: false
    webauthn:
      disable: true
    authentication_backend:
      disable_reset_password: false
      file:
        path: /config/users_database.yml
        password:
          algorithm: argon2id
          iterations: 1
          key_length: 32
          salt_length: 16
          memory: 512
          parallelism: 8
    access_control:
      default_policy: deny
      rules:
        - domain:
          - yourdomain.com
          - "*.yourdomain.com"
          networks:
          - 192.168.4.0/24
          policy: bypass
        - domain:
          - yourdomain.com
          - "*.yourdomain.com"
          policy: two_factor
    session:
      name: authelia_session
      secret: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      expiration: 4h
      inactivity: 45m
      remember_me_duration: 1M
      domain: yourdomain.com
      redis:
        host: redis.authelia.svc.cluster.local
        port: 6379
        # This secret can also be set using the env variables AUTHELIA_SESSION_REDIS_PASSWORD
        password: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        # This is the Redis DB 
        database_index: 0
    regulation:
      max_retries: 3
      find_time: 2m
      ban_time: 5m
    storage:
      encryption_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
      mysql:
        host: mariadb.authelia.svc.cluster.local
        port: 3306
        database: authelia
        username: authelia
        password: xxxxxxxxxxxxxxxxxxxxxxxxxx
    notifier:
      disable_startup_check: false
      filesystem:
        filename: /tmp/notification.txt

  users_database.yml: |
    users:
      michael:
        displayname: "xxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        password: "$argon2id$v=19$m=65536,t=1,p=xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
        email: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
        groups:
          - admins
          - dev
# For password hash generation use https://argon2.online/
# Choose params:
# type: `argon2id`
# Memory cost: `128`
# hash length: `32`
# parallelism: `8`
# iterations: `2` 
# Mount files that are going to be modified by authelia in /tmp instead of /config default path