apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- authelia-config.yaml
secretGenerator:
- name: env-secrets
  namespace: authelia
  files:
  - secret/MYSQL_DATABASE
  - secret/MYSQL_PASSWORD
  - secret/MYSQL_ROOT_PASSWORD
  - secret/MYSQL_USER
  - secret/PGID
  - secret/PUID
  - secret/REDIS_PASS
  - secret/TZ
