apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: longhorn
  namespace: kube-system
spec:
  chart: longhorn
  name: longhorn
  repo: https://charts.longhorn.io
  targetNamespace: longhorn-system
  version: v1.2.4
  valuesContent: |-
    persistence:
      defaultClassReplicaCount: 3
      reclaimPolicy: Retain
    defaultSettings:
      defaultDataLocality: best-effort
      replicaAutoBalance: best-effort