namespace: longhorn-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ingress.yaml
- namespace.yaml
helmCharts:
- name: longhorn
  namespace: longhorn-system
  releaseName: longhorn
  repo: https://charts.longhorn.io
  valuesFile: values.yaml
  version: 'v1.2.4'
