apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: cert-manager
  namespace: kube-system
spec:
  chart: cert-manager
  repo: https://charts.jetstack.io
  set:
    installCRDs: "true"
    podDnsPolicy: None
  targetNamespace: cert-manager
  valuesContent: |-
    deploymentAnnotations:
      certmanager.k8s.io/disable-validation: "true"
    podDnsConfig:
      nameservers:
        - 1.1.1.1
        - 1.0.0.1
  version: v1.8.0
