apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: xxxxxxxxxxxxxxxxxxxx
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
      - dns01:
          cloudflare:
            email: xxxxxxxxxxxxxxxxxxxx
            apiTokenSecretRef:
              name: cloudflare-api-token-secret
              key: api-token