apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-pvc
  namespace: diun
spec:
  resources:
    requests:
      storage: 2Gi
  accessModes:
  - ReadWriteMany
  storageClassName: longhorn
