apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- blocky.yaml
- blocky-svc.yaml
- redis.yml
- redis-svc.yml
images:
- name: ghcr.io/0xerr0r/blocky
  newTag: "v0.18"
- name: redis
  newTag: "7.0.0-alpine"
