apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  name: diun
  kind: ClusterRole
  apiGroup: rbac.authorization.k8s.io
subjects:
- name: diun
  namespace: diun
  kind: ServiceAccount
