apiVersion: v1
kind: Service
metadata:
  name: scrypted
  namespace: scrypted
  labels:
    name: scrypted
spec:
  selector:
    app: scrypted
  ports:
  - name: http
    protocol: TCP
    port: 11080
    targetPort: 11080
