namespace: changedetection
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- ingress.yaml
- namespace.yaml
- service.yaml
images:
- name: dgtlmoon/changedetection.io
  newTag: "0.39.13.1"
