apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: thelounge
  namespace: thelounge
spec:
  entryPoints:
  - websecure
  routes:
  - kind: Rule
    match: Host(`your.domain.com`)
    middlewares:
    - name: chain-authelia
      namespace: default
    services:
    - name: thelounge
      namespace: thelounge
      port: 9000
