apiVersion: v1
kind: Service
metadata:
  name: thelounge
  namespace: thelounge
  labels:
    name: thelounge
spec:
  selector:
    app: thelounge
  ports:
  - name: http
    protocol: TCP
    port: 9000
    targetPort: 9000
