apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
patchesStrategicMerge:
- deployment.yaml
secretGenerator:
- name: ddclient-config
  namespace: ddclient
  files:
  - secret/ddclient.conf
