namespace: metallb-system
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
helmCharts:
- name: metallb
  namespace: metallb-system
  releaseName: metallb
  repo: https://metallb.github.io/metallb
  valuesFile: values.yaml
  version: '0.12.1'
